blog/urls.py
from django.urls import path

from blog import views

app_name = "blog"

urlpatterns = [
    path(
        "",
        views.view_blog,
        name="blog",
    ),
    path("page/<int:page_id_src>", views.view_page, name="page_blog"),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = "cart"

urlpatterns = [
    path("order/", views.view_order, name="order"),
    path(
        "add/",
        views.add_to_cart,
        name="add_to_cart",
    ),
    path(
        "del/",
        views.del_to_cart,
        name="del_to_cart",
    ),
    path(
        "notify_product/",
        views.notify_product_cart,
        name="notify_product_cart",
    ),
    path(
        "",
        views.view_cart,
        name="cart",
    ),
]

diplom_django_netology/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from article import views
from catalog.views import main_catalog

urlpatterns = [
    path("catalog/", include(("catalog.urls", "catalog"), namespace="catalog")),
    path("cart/", include("cart.urls")),
    path("blog/", include("blog.urls")),
    path("account/", include("account.urls")),
    path("admin/", admin.site.urls),
    path("event/", views.view_event, name="event"),
    path("", views.view_home, name="home"),
    path("search/", views.SearchResultsView.as_view(), name="search_results"),
    path("contacts/", include("contacts.urls")),
    path("catalog_main/", main_catalog, name="main_catalog"),
    path("captcha/", include("captcha.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

cart/models.py
from django.db import models

# from django.contrib.auth.models import User
from account.models import User
from catalog.models import Product


class Order(models.Model):
    customer = models.ForeignKey(
        User,
        related_name="customer",
        on_delete=models.CASCADE,
        verbose_name="Покупатель",
    )
    products = models.ManyToManyField(
        Product, verbose_name="Товары", blank=True, through="ProductsInOrder"
    )
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата и время создания"
    )

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return f"{self.customer} - {self.created}"


class ProductsInOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name="Товар",
        related_name="count_in_order",
    )
    quantity = models.PositiveSmallIntegerField(
        verbose_name="Количество товара в заказе"
    )

cart/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect


from account.models import User
from cart.models import Order, ProductsInOrder
from catalog.models import Product


import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from contacts.models import SendMailContacts
from diplom_django_netology import configure


from cloudipsp import Api, Checkout


def add_to_cart(request):
    path = request.GET.get("next")
    if request.method == "POST":
        product_id = request.GET.get("product_id")
        if "cart" not in request.session:
            request.session["cart"] = {}
        cart = request.session.get("cart")
        if product_id in cart:
            cart[product_id]["quantity"] += 1
        else:
            cart[product_id] = {"quantity": 1}
    request.session.modified = True
    return redirect(path)


def del_to_cart(request):
    if request.method == "POST":
        product_id = request.GET.get("product_id")
        cart = request.session.get("cart")
        val_del = True
        if cart[product_id]["quantity"] > 1:
            val_del = False
            cart[product_id]["quantity"] -= 1
        if cart[product_id]["quantity"] == 1 and val_del:
            del cart[product_id]
    request.session.modified = True
    return redirect("/cart/")


def sendOneMail(titleProduct, toaddr):
    info = "Нехватка товара: " + titleProduct
    text_info = ". Есть спрос на товар которого нет. Возможно вы не указали наличине его в админ панели."
    msg = MIMEMultipart()
    msg["From"] = configure.SERVER_EMAIL
    msg["To"] = toaddr
    msg["Subject"] = info
    body = info + "\n\n" + info + text_info
    msg.attach(MIMEText(body, "plain"))
    server = smtplib.SMTP(configure.EMAIL_HOST, configure.EMAIL_PORT)
    server.ehlo()
    server.starttls()
    server.login(configure.SERVER_EMAIL, configure.EMAIL_HOST_PASSWORD)
    text = msg.as_string()
    server.sendmail(configure.SERVER_EMAIL, toaddr, text)
    server.quit()


def sendMail(titleProduct):
    allMail = SendMailContacts.objects.all()
    for i in allMail:
        sendOneMail(titleProduct, i.email)
    sendOneMail(titleProduct, toaddr)


def notify_product_cart(request):
    path = request.GET.get("next")
    if request.method == "POST":
        product_title = request.GET.get("product_title")
        sendMail(product_title)

    return redirect(path)


def saleOneFun(object_list):
    object_list["valsale"] = False
    if object_list["sale"] != 1.0:
        object_list["valsale"] = True
        object_list["saleprice"] = object_list["price"] * object_list["sale"]
        object_list["htmlprice"] = str(100 - object_list["sale"] * 100) + "%"
    return object_list


api = Api(merchant_id=configure.cloudipsp_merchant_id, secret_key=configure.cloudipsp_secret_key)
checkout = Checkout(api=api)


def payment(cout, text):
    coutS = str(cout).split(".")
    if len(coutS[1]) == 1:
        cout = int(coutS[0] + coutS[1] + "0")
    else:
        cout = int(coutS[0] + coutS[1])
    data = {"currency": "RUB", "amount": cout, "order_desc": text}
    return checkout.url(data).get("checkout_url")


def view_cart(request):
    if request.POST.get("order_status") == "approved":
        request.session["cart"] = {}
        request.session.modified = True
        messages.success(request, "Заказ принят")
    context = {}
    cart = request.session.get("cart", None)
    if cart:
        products = {}
        product_list = Product.objects.filter(pk__in=cart.keys()).values(
            "id", "title", "description", "price", "sale"
        )

        for product in product_list:
            products[str(product["id"])] = product
        for key in cart.keys():
            cart[key]["product"] = saleOneFun(products[key])

        outPrice = 0
        outText = ""
        for p in cart:
            p = cart[p]
            outText += p["product"]["title"] + " × " + str(p["quantity"]) + "; "
            for i in range(p["quantity"]):
                if p["product"]["valsale"]:
                    outPrice += p["product"]["saleprice"]
                else:
                    outPrice += p["product"]["price"]
        context["paymentUrl"] = payment(outPrice, outText)
        context["outPrice"] = outPrice
        context["cart"] = cart
    return render(request, "cart.html", context)


@login_required(login_url="login")
def view_order(request):
    if request.method == "POST":
        user_id = request.user.pk
        customer = User.objects.get(pk=user_id)
        cart = request.session["cart"]
        if len(cart) > 0:
            order = Order.objects.create(customer=customer)
            for key, value in cart.items():
                product = Product.objects.get(pk=key)
                quantity = value["quantity"]
                ProductsInOrder.objects.create(
                    order=order, product=product, quantity=quantity
                )
            request.session["cart"] = {}
            request.session.modified = True
            messages.success(request, "Заказ принят")
    return redirect("cart:cart")

cart/templates/add_to_cart.html
<form action="{% url 'cart:add_to_cart' %}?product_id={{ product.id }}&next={{ request.path }}" method="post">
    {% csrf_token %}
    
    <input type="submit" class="btn btn-secondary" value="Добавить в корзину »">
</form>

cart/templates/add_to_cart_detail.html
{% if product.count > 0 %}
<form action="{% url 'cart:add_to_cart' %}?product_id={{ product.id }}&next={{ request.path }}" method="post">
    {% csrf_token %}
    
    <input type="submit" class="btn btn-secondary" value="Добавить в корзину »">
</form>
{% endif %}
{% if product.count < 1 %}
<form action="{% url 'cart:notify_product_cart' %}?product_title={{ product.title }}&next={{ request.path }}" method="post">
    {% csrf_token %}
    
    <input type="submit" class="btn btn-secondary" value="Уведомить о отсутсвии товара »">
</form>
{% endif %}

cart/templates/cart.html
{% extends 'base.html' %}

{% block title %}Корзина{% endblock %}


{% block content %}
    <div class="container mt-3">




    {% if not cart %}

    <div class="col-lg-6 col-md-9 col-sm-12 order-md-2 mb-4 mx-auto">
        <h4 class="text-muted">В корзине пока что нет товаров</h4>
    </div>

{% else %}

    <div class="row">
        <div class="col-lg-6 col-md-9 col-sm-12 order-md-2 mb-4 mx-auto">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Ваша корзина</span>
                <span class="badge badge-secondary badge-pill">{{ cart|length }}</span>
            </h4>
            <ul class="list-group mb-3">

                {% for value in cart.values %}
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            <h6 class="my-0">{{ value.product.title}}</h6>
                            <small class="text-muted">Цена: {{ value.product.price }} рублей</small>
                            {% if value.product.valsale %}
                            <small class="text-muted">Скидка: {{ value.product.htmlprice }}</small><br>
                            <small class="text-muted">Итоговая цена: {{ value.product.saleprice }} рублей</small>
                            {% endif %}
                        </div>
                        <span class="text-muted">
                        <form action="{% url 'cart:del_to_cart' %}?product_id={{ value.product.id }}" method="post"><b>{{ value.quantity }}</b>&nbsp;&nbsp;
                            {% csrf_token %}    
                            <input type="submit" class="" value="&#10006;">
                        </form></span>

                    </li>
                {% endfor %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Итоговая сумма: {{ outPrice }} рублей</h6>
              </div>
            </li>
            </ul>
            <div class="card p-2">
            <a href="{{ paymentUrl }}" class="btn btn-secondary">Оплатить</a>
            </div>
            <!--
            <form class="card p-2" action="{% url 'cart:order' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-secondary">Заказать</button>
            </form>-->
        </div>
    </div>
{% endif %}
    {% if messages %}
    {% for message in messages %}
    <p class="text-success text-center">{{ message }}</p>
    {% endfor %}
{% endif %}

    </div>
{% endblock %}